//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSvcAndaluciaCuadre.CargarDatosSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCargaDatos", Namespace="http://schemas.frameworks.com.ec/ProyectoAndaluciaSvc/2020/9")]
    [System.SerializableAttribute()]
    public partial class clsCargaDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiasIniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechadesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinmesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiasIni {
            get {
                return this.DiasIniField;
            }
            set {
                if ((this.DiasIniField.Equals(value) != true)) {
                    this.DiasIniField = value;
                    this.RaisePropertyChanged("DiasIni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encaje {
            get {
                return this.EncajeField;
            }
            set {
                if ((object.ReferenceEquals(this.EncajeField, value) != true)) {
                    this.EncajeField = value;
                    this.RaisePropertyChanged("Encaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierre {
            get {
                return this.FechaCierreField;
            }
            set {
                if ((this.FechaCierreField.Equals(value) != true)) {
                    this.FechaCierreField = value;
                    this.RaisePropertyChanged("FechaCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaHasta {
            get {
                return this.FechaHastaField;
            }
            set {
                if ((this.FechaHastaField.Equals(value) != true)) {
                    this.FechaHastaField = value;
                    this.RaisePropertyChanged("FechaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSd {
            get {
                return this.FechaSdField;
            }
            set {
                if ((this.FechaSdField.Equals(value) != true)) {
                    this.FechaSdField = value;
                    this.RaisePropertyChanged("FechaSd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fechadesde {
            get {
                return this.FechadesdeField;
            }
            set {
                if ((this.FechadesdeField.Equals(value) != true)) {
                    this.FechadesdeField = value;
                    this.RaisePropertyChanged("Fechadesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Finmes {
            get {
                return this.FinmesField;
            }
            set {
                if ((object.ReferenceEquals(this.FinmesField, value) != true)) {
                    this.FinmesField = value;
                    this.RaisePropertyChanged("Finmes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsResultado", Namespace="http://schemas.frameworks.com.ec/Games/2017/01")]
    [System.SerializableAttribute()]
    public partial class clsResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodTranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalContField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalDifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoriza {
            get {
                return this.AutorizaField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaField, value) != true)) {
                    this.AutorizaField = value;
                    this.RaisePropertyChanged("Autoriza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodTran {
            get {
                return this.CodTranField;
            }
            set {
                if ((this.CodTranField.Equals(value) != true)) {
                    this.CodTranField = value;
                    this.RaisePropertyChanged("CodTran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierre {
            get {
                return this.FechaCierreField;
            }
            set {
                if ((this.FechaCierreField.Equals(value) != true)) {
                    this.FechaCierreField = value;
                    this.RaisePropertyChanged("FechaCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSd {
            get {
                return this.FechaSdField;
            }
            set {
                if ((this.FechaSdField.Equals(value) != true)) {
                    this.FechaSdField = value;
                    this.RaisePropertyChanged("FechaSd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar1 {
            get {
                return this.MensajeAuxiliar1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar1Field, value) != true)) {
                    this.MensajeAuxiliar1Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar2 {
            get {
                return this.MensajeAuxiliar2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar2Field, value) != true)) {
                    this.MensajeAuxiliar2Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar3 {
            get {
                return this.MensajeAuxiliar3Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar3Field, value) != true)) {
                    this.MensajeAuxiliar3Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalCont {
            get {
                return this.TotalContField;
            }
            set {
                if ((this.TotalContField.Equals(value) != true)) {
                    this.TotalContField = value;
                    this.RaisePropertyChanged("TotalCont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalDif {
            get {
                return this.TotalDifField;
            }
            set {
                if ((this.TotalDifField.Equals(value) != true)) {
                    this.TotalDifField = value;
                    this.RaisePropertyChanged("TotalDif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPaginas {
            get {
                return this.TotalPaginasField;
            }
            set {
                if ((this.TotalPaginasField.Equals(value) != true)) {
                    this.TotalPaginasField = value;
                    this.RaisePropertyChanged("TotalPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalProducto {
            get {
                return this.TotalProductoField;
            }
            set {
                if ((this.TotalProductoField.Equals(value) != true)) {
                    this.TotalProductoField = value;
                    this.RaisePropertyChanged("TotalProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsFiltro", Namespace="http://schemas.datacontract.org/2004/07/ProyectoAndaluciaSvc.DTO")]
    [System.SerializableAttribute()]
    public partial class clsFiltro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FilasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiltroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ModoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> OficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_cadenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> p_filialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> p_modoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> p_oficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string p_sesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> trnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Filas {
            get {
                return this.FilasField;
            }
            set {
                if ((this.FilasField.Equals(value) != true)) {
                    this.FilasField = value;
                    this.RaisePropertyChanged("Filas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filtro {
            get {
                return this.FiltroField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltroField, value) != true)) {
                    this.FiltroField = value;
                    this.RaisePropertyChanged("Filtro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Modo {
            get {
                return this.ModoField;
            }
            set {
                if ((this.ModoField.Equals(value) != true)) {
                    this.ModoField = value;
                    this.RaisePropertyChanged("Modo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Oficina {
            get {
                return this.OficinaField;
            }
            set {
                if ((this.OficinaField.Equals(value) != true)) {
                    this.OficinaField = value;
                    this.RaisePropertyChanged("Oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdenField, value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pagina {
            get {
                return this.PaginaField;
            }
            set {
                if ((this.PaginaField.Equals(value) != true)) {
                    this.PaginaField = value;
                    this.RaisePropertyChanged("Pagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Rol {
            get {
                return this.RolField;
            }
            set {
                if ((this.RolField.Equals(value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_cadena {
            get {
                return this.p_cadenaField;
            }
            set {
                if ((object.ReferenceEquals(this.p_cadenaField, value) != true)) {
                    this.p_cadenaField = value;
                    this.RaisePropertyChanged("p_cadena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_filial {
            get {
                return this.p_filialField;
            }
            set {
                if ((this.p_filialField.Equals(value) != true)) {
                    this.p_filialField = value;
                    this.RaisePropertyChanged("p_filial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_login {
            get {
                return this.p_loginField;
            }
            set {
                if ((object.ReferenceEquals(this.p_loginField, value) != true)) {
                    this.p_loginField = value;
                    this.RaisePropertyChanged("p_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_modo {
            get {
                return this.p_modoField;
            }
            set {
                if ((this.p_modoField.Equals(value) != true)) {
                    this.p_modoField = value;
                    this.RaisePropertyChanged("p_modo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> p_oficina {
            get {
                return this.p_oficinaField;
            }
            set {
                if ((this.p_oficinaField.Equals(value) != true)) {
                    this.p_oficinaField = value;
                    this.RaisePropertyChanged("p_oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_operacion {
            get {
                return this.p_operacionField;
            }
            set {
                if ((object.ReferenceEquals(this.p_operacionField, value) != true)) {
                    this.p_operacionField = value;
                    this.RaisePropertyChanged("p_operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string p_sesion {
            get {
                return this.p_sesionField;
            }
            set {
                if ((object.ReferenceEquals(this.p_sesionField, value) != true)) {
                    this.p_sesionField = value;
                    this.RaisePropertyChanged("p_sesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> trn {
            get {
                return this.trnField;
            }
            set {
                if ((this.trnField.Equals(value) != true)) {
                    this.trnField = value;
                    this.RaisePropertyChanged("trn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsDiasFeriados", Namespace="http://schemas.frameworks.com.ec/ProyectoAndaluciaSvc/2020/9")]
    [System.SerializableAttribute()]
    public partial class clsDiasFeriados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((this.CiudadField.Equals(value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CargarDatosSvc.ICargaDatosSvc")]
    public interface ICargaDatosSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarDataResponse")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataResponse CargarData(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarDataResponse")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataResponse> CargarDataAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarDataFechas", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarDataFechasResponse")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasResponse CargarDataFechas(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarDataFechas", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarDataFechasResponse")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasResponse> CargarDataFechasAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2101", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2101Response")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Response CargarData2101(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2101", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2101Response")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Response> CargarData2101Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData210105", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData210105Response")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Response CargarData210105(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData210105", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData210105Response")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Response> CargarData210105Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2105", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2105Response")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Response CargarData2105(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2105", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2105Response")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Response> CargarData2105Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2103", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2103Response")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Response CargarData2103(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2103", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2103Response")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Response> CargarData2103Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2105PF", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2105PFResponse")]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFResponse CargarData2105PF(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargaDatosSvc/CargarData2105PF", ReplyAction="http://tempuri.org/ICargaDatosSvc/CargarData2105PFResponse")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFResponse> CargarData2105PFAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos Cuenta;
        
        public CargarDataRequest() {
        }
        
        public CargarDataRequest(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos Cuenta) {
            this.Cuenta = Cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarDataResponse() {
        }
        
        public CargarDataResponse(int CargarDataResult, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarDataResult = CargarDataResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarDataFechas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarDataFechasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsFiltro filtro;
        
        public CargarDataFechasRequest() {
        }
        
        public CargarDataFechasRequest(WinSvcAndaluciaCuadre.CargarDatosSvc.clsFiltro filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarDataFechasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarDataFechasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsDiasFeriados[] CargarDataFechasResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarDataFechasResponse() {
        }
        
        public CargarDataFechasResponse(WinSvcAndaluciaCuadre.CargarDatosSvc.clsDiasFeriados[] CargarDataFechasResult, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarDataFechasResult = CargarDataFechasResult;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2101", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2101Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos;
        
        public CargarData2101Request() {
        }
        
        public CargarData2101Request(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos) {
            this.CargaDatos = CargaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2101Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2101Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarData2101Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarData2101Response() {
        }
        
        public CargarData2101Response(int CargarData2101Result, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarData2101Result = CargarData2101Result;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData210105", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData210105Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos;
        
        public CargarData210105Request() {
        }
        
        public CargarData210105Request(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos) {
            this.CargaDatos = CargaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData210105Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData210105Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarData210105Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarData210105Response() {
        }
        
        public CargarData210105Response(int CargarData210105Result, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarData210105Result = CargarData210105Result;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2105", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2105Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos;
        
        public CargarData2105Request() {
        }
        
        public CargarData2105Request(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos) {
            this.CargaDatos = CargaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2105Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2105Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarData2105Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarData2105Response() {
        }
        
        public CargarData2105Response(int CargarData2105Result, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarData2105Result = CargarData2105Result;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2103", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2103Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos;
        
        public CargarData2103Request() {
        }
        
        public CargarData2103Request(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos) {
            this.CargaDatos = CargaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2103Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2103Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarData2103Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarData2103Response() {
        }
        
        public CargarData2103Response(int CargarData2103Result, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarData2103Result = CargarData2103Result;
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2105PF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2105PFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos;
        
        public CargarData2105PFRequest() {
        }
        
        public CargarData2105PFRequest(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos) {
            this.CargaDatos = CargaDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarData2105PFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarData2105PFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CargarData2105PFResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado;
        
        public CargarData2105PFResponse() {
        }
        
        public CargarData2105PFResponse(int CargarData2105PFResult, WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            this.CargarData2105PFResult = CargarData2105PFResult;
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargaDatosSvcChannel : WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargaDatosSvcClient : System.ServiceModel.ClientBase<WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc>, WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc {
        
        public CargaDatosSvcClient() {
        }
        
        public CargaDatosSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargaDatosSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargaDatosSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargaDatosSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataResponse WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest request) {
            return base.Channel.CargarData(request);
        }
        
        public int CargarData(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos Cuenta, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest();
            inValue.Cuenta = Cuenta;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataResponse retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData(inValue);
            resultado = retVal.resultado;
            return retVal.CargarDataResult;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataResponse> CargarDataAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataRequest request) {
            return base.Channel.CargarDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasResponse WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarDataFechas(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest request) {
            return base.Channel.CargarDataFechas(request);
        }
        
        public WinSvcAndaluciaCuadre.CargarDatosSvc.clsDiasFeriados[] CargarDataFechas(WinSvcAndaluciaCuadre.CargarDatosSvc.clsFiltro filtro, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest();
            inValue.filtro = filtro;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasResponse retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarDataFechas(inValue);
            resultado = retVal.resultado;
            return retVal.CargarDataFechasResult;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasResponse> CargarDataFechasAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarDataFechasRequest request) {
            return base.Channel.CargarDataFechasAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Response WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData2101(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request request) {
            return base.Channel.CargarData2101(request);
        }
        
        public int CargarData2101(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request();
            inValue.CargaDatos = CargaDatos;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Response retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData2101(inValue);
            resultado = retVal.resultado;
            return retVal.CargarData2101Result;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Response> CargarData2101Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2101Request request) {
            return base.Channel.CargarData2101Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Response WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData210105(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request request) {
            return base.Channel.CargarData210105(request);
        }
        
        public int CargarData210105(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request();
            inValue.CargaDatos = CargaDatos;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Response retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData210105(inValue);
            resultado = retVal.resultado;
            return retVal.CargarData210105Result;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Response> CargarData210105Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData210105Request request) {
            return base.Channel.CargarData210105Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Response WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData2105(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request request) {
            return base.Channel.CargarData2105(request);
        }
        
        public int CargarData2105(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request();
            inValue.CargaDatos = CargaDatos;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Response retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData2105(inValue);
            resultado = retVal.resultado;
            return retVal.CargarData2105Result;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Response> CargarData2105Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105Request request) {
            return base.Channel.CargarData2105Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Response WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData2103(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request request) {
            return base.Channel.CargarData2103(request);
        }
        
        public int CargarData2103(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request();
            inValue.CargaDatos = CargaDatos;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Response retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData2103(inValue);
            resultado = retVal.resultado;
            return retVal.CargarData2103Result;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Response> CargarData2103Async(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2103Request request) {
            return base.Channel.CargarData2103Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFResponse WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc.CargarData2105PF(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest request) {
            return base.Channel.CargarData2105PF(request);
        }
        
        public int CargarData2105PF(WinSvcAndaluciaCuadre.CargarDatosSvc.clsCargaDatos CargaDatos, out WinSvcAndaluciaCuadre.CargarDatosSvc.clsResultado resultado) {
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest inValue = new WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest();
            inValue.CargaDatos = CargaDatos;
            WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFResponse retVal = ((WinSvcAndaluciaCuadre.CargarDatosSvc.ICargaDatosSvc)(this)).CargarData2105PF(inValue);
            resultado = retVal.resultado;
            return retVal.CargarData2105PFResult;
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFResponse> CargarData2105PFAsync(WinSvcAndaluciaCuadre.CargarDatosSvc.CargarData2105PFRequest request) {
            return base.Channel.CargarData2105PFAsync(request);
        }
    }
}
