//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinSvcAndaluciaCuadre.SvcEnviarCorreo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCorreoAplicacion", Namespace="http://schemas.frameworks.com.ec/ProyectoCuadresSQL/2020/9")]
    [System.SerializableAttribute()]
    public partial class clsCorreoAplicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionarioTranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlantillaHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmtpServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SmtpServerPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmtpServerSslField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveOrigen {
            get {
                return this.ClaveOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveOrigenField, value) != true)) {
                    this.ClaveOrigenField = value;
                    this.RaisePropertyChanged("ClaveOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAplicacion {
            get {
                return this.CodigoAplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAplicacionField, value) != true)) {
                    this.CodigoAplicacionField = value;
                    this.RaisePropertyChanged("CodigoAplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncionarioTran {
            get {
                return this.FuncionarioTranField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionarioTranField, value) != true)) {
                    this.FuncionarioTranField = value;
                    this.RaisePropertyChanged("FuncionarioTran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logotipo {
            get {
                return this.LogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogotipoField, value) != true)) {
                    this.LogotipoField = value;
                    this.RaisePropertyChanged("Logotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantillaHtml {
            get {
                return this.PlantillaHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantillaHtmlField, value) != true)) {
                    this.PlantillaHtmlField = value;
                    this.RaisePropertyChanged("PlantillaHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmtpServer {
            get {
                return this.SmtpServerField;
            }
            set {
                if ((object.ReferenceEquals(this.SmtpServerField, value) != true)) {
                    this.SmtpServerField = value;
                    this.RaisePropertyChanged("SmtpServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SmtpServerPort {
            get {
                return this.SmtpServerPortField;
            }
            set {
                if ((this.SmtpServerPortField.Equals(value) != true)) {
                    this.SmtpServerPortField = value;
                    this.RaisePropertyChanged("SmtpServerPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmtpServerSsl {
            get {
                return this.SmtpServerSslField;
            }
            set {
                if ((object.ReferenceEquals(this.SmtpServerSslField, value) != true)) {
                    this.SmtpServerSslField = value;
                    this.RaisePropertyChanged("SmtpServerSsl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserOrigen {
            get {
                return this.UserOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOrigenField, value) != true)) {
                    this.UserOrigenField = value;
                    this.RaisePropertyChanged("UserOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsResultado", Namespace="http://schemas.frameworks.com.ec/ProyectoCuadresSQL/2020/9")]
    [System.SerializableAttribute()]
    public partial class clsResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodTranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeAuxiliar3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalRegistrosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autoriza {
            get {
                return this.AutorizaField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizaField, value) != true)) {
                    this.AutorizaField = value;
                    this.RaisePropertyChanged("Autoriza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodTran {
            get {
                return this.CodTranField;
            }
            set {
                if ((this.CodTranField.Equals(value) != true)) {
                    this.CodTranField = value;
                    this.RaisePropertyChanged("CodTran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar1 {
            get {
                return this.MensajeAuxiliar1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar1Field, value) != true)) {
                    this.MensajeAuxiliar1Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar2 {
            get {
                return this.MensajeAuxiliar2Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar2Field, value) != true)) {
                    this.MensajeAuxiliar2Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeAuxiliar3 {
            get {
                return this.MensajeAuxiliar3Field;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeAuxiliar3Field, value) != true)) {
                    this.MensajeAuxiliar3Field = value;
                    this.RaisePropertyChanged("MensajeAuxiliar3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPaginas {
            get {
                return this.TotalPaginasField;
            }
            set {
                if ((this.TotalPaginasField.Equals(value) != true)) {
                    this.TotalPaginasField = value;
                    this.RaisePropertyChanged("TotalPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalRegistros {
            get {
                return this.TotalRegistrosField;
            }
            set {
                if ((this.TotalRegistrosField.Equals(value) != true)) {
                    this.TotalRegistrosField = value;
                    this.RaisePropertyChanged("TotalRegistros");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcEnviarCorreo.INotificador")]
    public interface INotificador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreo", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoResponse")]
        WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsResultado EnviarCorreo(WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreo", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsResultado> EnviarCorreoAsync(WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreoVarios", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoVariosResponse")]
        int EnviarCorreoVarios(string[] correosDesstino, WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreoVarios", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoVariosResponse")]
        System.Threading.Tasks.Task<int> EnviarCorreoVariosAsync(string[] correosDesstino, WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificadorChannel : WinSvcAndaluciaCuadre.SvcEnviarCorreo.INotificador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificadorClient : System.ServiceModel.ClientBase<WinSvcAndaluciaCuadre.SvcEnviarCorreo.INotificador>, WinSvcAndaluciaCuadre.SvcEnviarCorreo.INotificador {
        
        public NotificadorClient() {
        }
        
        public NotificadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsResultado EnviarCorreo(WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreo(datosCorreo, asunto, parametros, anexos);
        }
        
        public System.Threading.Tasks.Task<WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsResultado> EnviarCorreoAsync(WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoAsync(datosCorreo, asunto, parametros, anexos);
        }
        
        public int EnviarCorreoVarios(string[] correosDesstino, WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoVarios(correosDesstino, datosCorreo, asunto, parametros, anexos);
        }
        
        public System.Threading.Tasks.Task<int> EnviarCorreoVariosAsync(string[] correosDesstino, WinSvcAndaluciaCuadre.SvcEnviarCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoVariosAsync(correosDesstino, datosCorreo, asunto, parametros, anexos);
        }
    }
}
