//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAndalucia.NotificacionCorreo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsCorreoAplicacion", Namespace="http://schemas.frameworks.com.ec/ProyectoCuadresSQL/2020/9")]
    [System.SerializableAttribute()]
    public partial class clsCorreoAplicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncionarioTranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlantillaHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmtpServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SmtpServerPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmtpServerSslField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveOrigen {
            get {
                return this.ClaveOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveOrigenField, value) != true)) {
                    this.ClaveOrigenField = value;
                    this.RaisePropertyChanged("ClaveOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAplicacion {
            get {
                return this.CodigoAplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAplicacionField, value) != true)) {
                    this.CodigoAplicacionField = value;
                    this.RaisePropertyChanged("CodigoAplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destino {
            get {
                return this.DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinoField, value) != true)) {
                    this.DestinoField = value;
                    this.RaisePropertyChanged("Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firma {
            get {
                return this.FirmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaField, value) != true)) {
                    this.FirmaField = value;
                    this.RaisePropertyChanged("Firma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncionarioTran {
            get {
                return this.FuncionarioTranField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionarioTranField, value) != true)) {
                    this.FuncionarioTranField = value;
                    this.RaisePropertyChanged("FuncionarioTran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logotipo {
            get {
                return this.LogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogotipoField, value) != true)) {
                    this.LogotipoField = value;
                    this.RaisePropertyChanged("Logotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlantillaHtml {
            get {
                return this.PlantillaHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.PlantillaHtmlField, value) != true)) {
                    this.PlantillaHtmlField = value;
                    this.RaisePropertyChanged("PlantillaHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmtpServer {
            get {
                return this.SmtpServerField;
            }
            set {
                if ((object.ReferenceEquals(this.SmtpServerField, value) != true)) {
                    this.SmtpServerField = value;
                    this.RaisePropertyChanged("SmtpServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SmtpServerPort {
            get {
                return this.SmtpServerPortField;
            }
            set {
                if ((this.SmtpServerPortField.Equals(value) != true)) {
                    this.SmtpServerPortField = value;
                    this.RaisePropertyChanged("SmtpServerPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmtpServerSsl {
            get {
                return this.SmtpServerSslField;
            }
            set {
                if ((object.ReferenceEquals(this.SmtpServerSslField, value) != true)) {
                    this.SmtpServerSslField = value;
                    this.RaisePropertyChanged("SmtpServerSsl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserOrigen {
            get {
                return this.UserOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOrigenField, value) != true)) {
                    this.UserOrigenField = value;
                    this.RaisePropertyChanged("UserOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificacionCorreo.INotificador")]
    public interface INotificador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreo", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoResponse")]
        DATA.clsResultado EnviarCorreo(ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreo", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<DATA.clsResultado> EnviarCorreoAsync(ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreoVarios", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoVariosResponse")]
        int EnviarCorreoVarios(string[] correosDesstino, ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificador/EnviarCorreoVarios", ReplyAction="http://tempuri.org/INotificador/EnviarCorreoVariosResponse")]
        System.Threading.Tasks.Task<int> EnviarCorreoVariosAsync(string[] correosDesstino, ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificadorChannel : ProyectoAndalucia.NotificacionCorreo.INotificador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificadorClient : System.ServiceModel.ClientBase<ProyectoAndalucia.NotificacionCorreo.INotificador>, ProyectoAndalucia.NotificacionCorreo.INotificador {
        
        public NotificadorClient() {
        }
        
        public NotificadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DATA.clsResultado EnviarCorreo(ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreo(datosCorreo, asunto, parametros, anexos);
        }
        
        public System.Threading.Tasks.Task<DATA.clsResultado> EnviarCorreoAsync(ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoAsync(datosCorreo, asunto, parametros, anexos);
        }
        
        public int EnviarCorreoVarios(string[] correosDesstino, ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoVarios(correosDesstino, datosCorreo, asunto, parametros, anexos);
        }
        
        public System.Threading.Tasks.Task<int> EnviarCorreoVariosAsync(string[] correosDesstino, ProyectoAndalucia.NotificacionCorreo.clsCorreoAplicacion datosCorreo, string asunto, System.Collections.Generic.Dictionary<string, string> parametros, string[] anexos) {
            return base.Channel.EnviarCorreoVariosAsync(correosDesstino, datosCorreo, asunto, parametros, anexos);
        }
    }
}
